<?php 
//INSERT INTO `mohsin13_dev`.`KNP_INVENTORY_TRANSACTION`(`INV_TRANS_ID`,`DONAR_UID`,`BENEFICIARY_UID`,`ASSIGN_QUEST_ID`,`INVENTORY_ID`,`CRAFT_ID`,`UNIT_TRANSFER`,`TRANS_TYPE`,`COMMENTS`,`TIMESTAMP`) VALUES ( NULL,'10000007','10000001',NULL,'10001',NULL,'1','TRADE','Trading inventory',CURRENT_TIMESTAMP);
?>